Laboratory work 2/WebTechnology/WebTechnology.movieSite/Controllers/CartoonController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WebTechnology.movieSite.Controllers
{
    public class CartoonController : Controller
    {
        // GET: Cartoon
        public ActionResult Index()
        {
            return View();
        }
    }
}

Laboratory work 2/WebTechnology/WebTechnology.movieSite/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WebTechnology.movieSite.Controllers
{
    public class HomeController : Controller
    {
        // GET: Home
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            return Content("About .......... ");
        }

    }

}

Laboratory work 2/WebTechnology/WebTechnology.movieSite/Controllers/MovieController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WebTechnology.movieSite.Controllers
{
    public class MovieController : Controller
    {
        // GET: Movie
        public ActionResult Index()
        {
            return View();
        }
    }
}

Laboratory work 2/WebTechnology/WebTechnology.movieSite/Views/Cartoon/Index.cshtml
@{
    ViewBag.Title = "Cartoons";
}


@Html.Partial("_Carousel")



<!-- content container -->
<div class="container-fluid" id="content">

    <div class="row my-2">
        <div class="col-10 p-1 offset-1 categories">
            <div class="d-flex flex-wrap justify-content-around">
                <div class="item m-1 p-2">For Children</div>
                <div class="item m-1 p-2">For all ages</div>
            </div>
        </div>
    </div><!-- row -->
    <!-- row -->
    <div class="row text-center">

        @for (int i = 0; i < 6; i++)
        {<div class="col-lg-4 col-sm-6 col-xs-12 mb-2 px-2">
                <div class="card">
                    <img class="card-img-top img-fluid" src="~/Content/images/monsters.jpg" alt="Card image">
                    <div class="card-body">
                        <h4 class="card-title p-1"> Monsters vs Aliens</h4>
                        <p class="card-text p-1">
                            After Susan Murphy is struck by a meteor and grows to be 50 feet tall,
                            she's captured by the government and shuttled to a secret compound.
                        </p>
                        <a href="#" class="btn btn-info float-right m-1">See Details</a>
                    </div>
                </div>
            </div>

        }


    </div>
    <!-- row -->

</div>
<!-- /content container -->

Laboratory work 2/WebTechnology/WebTechnology.movieSite/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home";
}

@Html.Partial("_Carousel")
<!-- content container -->
<div class="container-fluid" id="content">

    <!-- row -->
    <div class="row">

        @for (int i = 0; i < 6; i++)
        {
            <div class="col-lg-4 col-sm-6 col-xs-12 mb-2 px-2">
                <div class="card">
                    <img class="card-img-top img-fluid" src="~/Content/images/batmanVSsuperman.jpg" alt="Card image">
                    <div class="card-body">
                        <h4 class="card-title p-1">Batman vs Superman</h4>
                        <p class="card-text p-1">
                            Fearing that the actions of Superman are left unchecked,
                            Batman takes on the Man of Steel, while the world wrestles with what
                            kind of a hero it really needs.
                        </p>
                        <a href="#" class="btn btn-info float-right m-1">See Details</a>
                    </div>
                </div>
            </div>
        }

    </div><!-- row -->

</div>
<!-- /content container -->

Laboratory work 2/WebTechnology/WebTechnology.movieSite/Views/Movie/Index.cshtml
@{
    ViewBag.Title = "Movies";
}





@{
    ViewBag.Title = "Home";
}

@Html.Partial("_Carousel")
<!-- content container -->
<div class="container-fluid" id="content">
    <!-- row -->
    <div class="row my-2">
        <div class="col-10 p-1 offset-1 categories">
            <div class="d-flex flex-wrap justify-content-around">
                <div class="item m-1">Comedy</div>
                <div class="item m-1">Actions</div>
                <div class="item m-1">Detective</div>
                <div class="item m-1">Drama</div>
                <div class="item m-1">Historical</div>
                <div class="item m-1">Horrors</div>
            </div>
        </div>
    </div><!-- row -->
    <!-- row -->
    <div class="row text-center">

        @for (int i = 0; i < 6; i++)
        {
            <div class="col-lg-4 col-sm-6 col-xs-12 mb-2 px-2">
                <div class="card">
                    <img class="card-img-top img-fluid" src="~/Content/images/hangOver.jpg" alt="Card image">
                    <div class="card-body">
                        <h4 class="card-title p-1">Hang Over</h4>
                        <p class="card-text p-1">
                            When one of their own is kidnapped by an angry gangster, the Wolf Pack must
                            track down Mr. Chow, who has escaped from prison and is on the run.
                        </p>
                        <a href="#" class="btn btn-info float-right m-1">See Details</a>
                    </div>
                </div>
            </div>

        }

    </div><!-- row -->

</div>
<!-- /content container -->

Laboratory work 2/WebTechnology/WebTechnology.movieSite/Views/Shared/_Carousel.cshtml
<!-- Carousel -->
<div id="carouselExampleIndicators" class="carousel slide my-2" data-ride="carousel">
    <ol class="carousel-indicators">
        <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
        <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
        <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
    </ol>
    <div class="carousel-inner" role="listbox">
        <div class="carousel-item active">
            <img class="d-block img-fluid carouselImg" src="~/Content/images/Wonder-TWITTER-FB-OG.jpg" alt="First slide">
        </div>
        <div class="carousel-item">
            <img class="d-block img-fluid carouselImg" src="~/Content/images/murder on the orient express.jpg"
                 alt="Second slide">
        </div>
        <div class="carousel-item">
            <img class="d-block img-fluid carouselImg" src="~/Content/images/it-film.jpg" alt="Third slide">
        </div>
    </div>
    <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
    </a>
    <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
    </a>
</div>
<!-- /Carousel -->

Laboratory work 2/WebTechnology/WebTechnology.movieSite/Views/Shared/_Layout.cshtml
@using System.Web.Optimization
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - BestMovies</title>
    @Styles.Render("~/Content/css")
</head>
<body>
    @Html.Partial("_NavBar")
    

        @RenderBody()

    
    @Html.Partial("_Footer")

@Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/myScript")
    @RenderSection("scripts", required: false)
</body>
</html>

Laboratory work 2/WebTechnology/WebTechnology.movieSite/Views/Shared/_NavBar.cshtml
<!-- Header -->
<header>
    <nav class="navbar navbar-toggleable-md  navbar-inverse bg-inverse">
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo01"
                aria-controls="navbarTogglerDemo01" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarTogglerDemo01">
            <a class="navbar-brand" href="#">
                <img class="logoImg" src="~/Content/images/movielogo.png">
                <span class="ml-3 mr-5">Best Movies</span>
            </a>
            <ul class="navbar-nav mr-auto">
                <li class="nav-item ">
                         @Html.ActionLink("Most Popular", "Index", "Home", null, new { @class = "nav-link" })
                </li>
                <li class="nav-item">
                        @Html.ActionLink("Movies", "Index", "Movie", null, new { @class = "nav-link" })

                </li>
                <li class="nav-item">
                        @Html.ActionLink("Cartoons", "Index", "Cartoon", null, new { @class = "nav-link" })

                </li>
                <li class="nav-item">
                        @Html.ActionLink("Sign up", "Sign_up", "Account", null, new { @class = "nav-link" })

                </li>
                <li class="nav-item">
                        @Html.ActionLink("Sign in", "Sign_in", "Account", null, new { @class = "nav-link" })
                </li>
            </ul>
            <form class="form-inline">
                <input class="form-control" type="text" placeholder="Search">
                <button class="btn btn-outline-success " type="submit">Search</button>
            </form>
        </div>
    </nav>
</header>
<!-- /Header -->